display_information:
  name: Valet
features:
  app_home:
    home_tab_enabled: true
    messages_tab_enabled: false
    messages_tab_read_only_enabled: true
  bot_user:
    display_name: Valet
    always_online: true
  slash_commands:
    - command: /parking
      url: https://87ff-89-64-1-231.eu.ngrok.io/slack/events
      description: Tell the Valet what to do
      usage_hint: "[command] [args]"
      should_escape: false
oauth_config:
  scopes:
    bot:
      - im:history
      - im:write
      - im:read
      - chat:write
      - commands
settings:
  event_subscriptions:
    request_url: https://87ff-89-64-1-231.eu.ngrok.io/slack/events
    bot_events:
      - app_home_opened
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
